# Generated by Django 3.1.1 on 2020-09-07 07:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_auto_20200907_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('image',
                 models.ImageField(blank=True, null=True, upload_to=account.models.image_path, verbose_name='Picture')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Upload Time')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                   verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile Picture',
                'verbose_name_plural': 'Profile Pictures',
            },
        ),
    ]
