# Generated by Django 3.2.5 on 2021-07-21 20:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210721_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded'),
        ),
    ]
