# Generated by Django 3.1.1 on 2020-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Timestamp'),
        ),
    ]
