# Generated by Django 3.1.1 on 2020-09-11 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_auto_20200907_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='account_followers', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='account_following', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Following'),
        ),
    ]
