# Generated by Django 3.2.5 on 2021-07-28 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_remove_profilepicture_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.-]+\\Z', 'Enter a valid username. This value may contain only letters, numbers and ./-/_ characters.')], verbose_name='Username'),
        ),
    ]
