# Generated by Django 3.1.1 on 2020-09-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_auto_20200912_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, default='public', max_length=10, verbose_name='Account Type'),
        ),
    ]
