# Generated by Django 3.1.1 on 2020-09-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200916_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='About'),
        ),
    ]
