# Generated by Django 3.2.5 on 2021-07-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='OTP'),
        ),
    ]
