# Generated by Django 3.1.1 on 2020-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0008_account_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
