# Generated by Django 3.2.5 on 2021-07-29 03:11

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=account.models.get_otp_expires_at, editable=False, verbose_name='Expires At'),
        ),
    ]
