# Generated by Django 3.2.5 on 2021-07-20 20:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('image',
                 models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location, verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='Body')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Draft Status')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Timestamp')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                             verbose_name='Author')),
                ('likes',
                 models.ManyToManyField(blank=True, related_name='blog_post_likes', to=settings.AUTH_USER_MODEL,
                                        verbose_name='Likes')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
    ]
