# Generated by Django 3.2.5 on 2021-07-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210721_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date_updated',
            new_name='last_updated',
        ),
    ]
