# Generated by Django 3.2.5 on 2021-07-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_date_updated_blogpost_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='About'),
        ),
    ]
