# Generated by Django 3.1.1 on 2020-09-07 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_blogpost_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
    ]
