# Generated by Django 3.1.1 on 2020-09-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Timestamp'),
        ),
    ]
