# Generated by Django 3.2.5 on 2021-07-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
