# Generated by Django 3.1.1 on 2020-09-11 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_blogpost_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Draft Status'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
    ]
