# Generated by Django 3.2.5 on 2021-07-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Post Image', 'verbose_name_plural': 'Post Images'},
        ),
    ]
