# Generated by Django 3.2.5 on 2021-07-17 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=150, null=True, verbose_name='SenderID')),
                ('message', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Text')),
                ('timestamp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Timestamp')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserID')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
    ]
